### ISSUE TITLE
vue + ffmpeg

### ISSUE THREAD

**Issue by walnutYa** [littlebaozi/rtsp-web#13]
请问vue能直接结合ffmpeg做推拉流吗？还是必须要结合node端去做处理

**Comment by littlebaozi** [comment]
> 请问vue能直接结合ffmpeg做推拉流吗？还是必须要结合node端去做处理
推拉流都是服务端处理，前端只是播放

**Comment by walnutYa** [comment]
大神，你的这个demo能做推流吗？还有个问题是，拉流的时候，发现能播放，但是没有声音，请问在哪里可以控制？

**Comment by littlebaozi** [comment]
> 大神，你的这个demo能做推流吗？还有个问题是，拉流的时候，发现能播放，但是没有声音，请问在哪里可以控制？

我这个当时是海康大华的摄像头，后端发过来的视频是rtsp，所以做了node转码。声音没有需求，只测试了视频播放。

我也没研究过，深入的技术也无法解答，这篇文章讲得很细[HTML5视频监控技术预研](https://blog.gmem.cc/research-on-html5-video-surveillance)，你可以看看

**Comment by walnutYa** [comment]
好的，谢谢大神。
